name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Split branch name
      env:
        BRANCH: ${{ github.ref }}
      id: split
      run: echo "::set-output name=fragment::${BRANCH##*/}"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: avalitan/aaps-builder:latest, avalitan/aaps-builder:${{ steps.split.outputs.fragment }}
